version: '3.9'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - order_system-test

  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test_app
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres_db:5432/test_db?schema=public"
    command: >
      sh -c "yarn prisma migrate dev --name init &&
       
             yarn test:integration"
    networks:
      - order_system-test

volumes:
  postgres_data:

networks:
  order_system-test:
    driver: bridge
